RED_MOVEMENT_SPEED = 0.1
BLUE_MOVEMENT_SPEED = 0.1

COHERENCE_FACTOR = 0.025
SEPARATION_FACTOR = 0.2
MATCH_FACTOR = 0.05
ENEMY_POSITION_FACTOR = 0.03

VISION_RANGE = 50
FLOCKING_RADIUS = 5
SEPARATION_DISTANCE = 1