RED_MOVEMENT_SPEED = 0.1
BLUE_MOVEMENT_SPEED = 0.1

COHERENCE_FACTOR = 0.0
SEPARATION_FACTOR = 0.1
MATCH_FACTOR = 0.0
ENEMY_POSITION_FACTOR = 0.7

VISION_RANGE = 20
FLOCKING_RADIUS = 5
SEPARATION_DISTANCE = 3